export const horariosGym = [
    {
        id: 1,
        seccion: 'LUNES, MIÉRCOLES Y VIERNES',
        dias: ['Lunes', 'Miércoles', 'Viernes'],
        disciplina: 'MUAY THAI',
        modalidad: 'Todos los niveles',
        horaInicio: '07:30',
        horaFin: '08:45',
        turnoFiltro: 'MAÑANA',
        lugar: 'TATAMI PRINCIPAL',
        instructor: 'Carlos "El Toro" Vega',
        cargo: 'KRU CERTIFICADO WBC',
        iniciales: 'CT',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 2,
        seccion: 'LUNES, MIÉRCOLES Y VIERNES',
        dias: ['Lunes', 'Miércoles', 'Viernes'],
        disciplina: 'ACONDICIONAMIENTO',
        modalidad: 'Fuerza & Movilidad',
        horaInicio: '10:00',
        horaFin: '11:15',
        turnoFiltro: 'MAÑANA',
        lugar: 'ZONA DE FUERZA',
        instructor: 'Sergio Ramos B.',
        cargo: 'PREPARADOR FÍSICO CSCS',
        iniciales: 'SR',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 3,
        seccion: 'LUNES, MIÉRCOLES Y VIERNES',
        dias: ['Lunes', 'Miércoles', 'Viernes'],
        disciplina: 'ACONDICIONAMIENTO',
        modalidad: 'Core & Flexibilidad',
        horaInicio: '15:00',
        horaFin: '16:15',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'ZONA DE FUERZA',
        instructor: 'Sergio Ramos B.',
        cargo: 'PREPARADOR FÍSICO CSCS',
        iniciales: 'SR',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 4,
        seccion: 'LUNES, MIÉRCOLES Y VIERNES',
        dias: ['Lunes', 'Miércoles', 'Viernes'],
        disciplina: 'BRAZILIAN JIU-JITSU',
        modalidad: 'Gi · Fundamentos',
        horaInicio: '16:15',
        horaFin: '17:30',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'TATAMI CENTRAL',
        instructor: 'Prof. Mateo Silva',
        cargo: 'FAIXA PRETA 2º DAN IBJJF',
        iniciales: 'MS',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 5,
        seccion: 'LUNES, MIÉRCOLES Y VIERNES',
        dias: ['Lunes', 'Miércoles', 'Viernes'],
        disciplina: 'MMA',
        modalidad: 'Striking & Grappling',
        horaInicio: '17:30',
        horaFin: '18:45',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'JAULA & TATAMI',
        instructor: 'Marcos Valenzuela',
        cargo: 'LUCHADOR PRO MMA / HEAD COACH',
        iniciales: 'MV',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 6,
        seccion: 'LUNES, MIÉRCOLES Y VIERNES',
        dias: ['Lunes', 'Miércoles', 'Viernes'],
        disciplina: 'MUAY THAI',
        modalidad: 'Avanzado & Clincs',
        horaInicio: '18:45',
        horaFin: '20:00',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'TATAMI 2',
        instructor: 'Carlos "El Toro" Vega',
        cargo: 'KRU CERTIFICADO WBC',
        iniciales: 'CT',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 7,
        seccion: 'LUNES, MIÉRCOLES Y VIERNES',
        dias: ['Lunes', 'Miércoles', 'Viernes'],
        disciplina: 'BOXEO',
        modalidad: 'Técnica & Sparring',
        horaInicio: '15:00',
        horaFin: '16:15',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'RING CENTRAL',
        instructor: 'Javier "Zurdo" Gómez',
        cargo: 'ENTRENADOR NACIONAL FEB',
        iniciales: 'JG',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 8,
        seccion: 'MARTES Y JUEVES',
        dias: ['Martes', 'Jueves'],
        disciplina: 'BRAZILIAN JIU-JITSU',
        modalidad: 'No-Gi Matinal',
        horaInicio: '07:30',
        horaFin: '08:45',
        turnoFiltro: 'MAÑANA',
        lugar: 'TATAMI CENTRAL',
        instructor: 'Prof. Mateo Silva',
        cargo: 'FAIXA PRETA 2º DAN IBJJF',
        iniciales: 'MS',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 9,
        seccion: 'MARTES Y JUEVES',
        dias: ['Martes', 'Jueves'],
        disciplina: 'ACONDICIONAMIENTO',
        modalidad: 'Movilidad & Cardio',
        horaInicio: '09:00',
        horaFin: '10:00',
        turnoFiltro: 'MAÑANA',
        lugar: 'ZONA DE FUERZA',
        instructor: 'Sergio Ramos B.',
        cargo: 'PREPARADOR FÍSICO CSCS',
        iniciales: 'SR',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 10,
        seccion: 'MARTES Y JUEVES',
        dias: ['Martes', 'Jueves'],
        disciplina: 'BOXEO',
        modalidad: 'Fundamentos',
        horaInicio: '10:00',
        horaFin: '11:00',
        turnoFiltro: 'MAÑANA',
        lugar: 'RING CENTRAL',
        instructor: 'Javier "Zurdo" Gómez',
        cargo: 'ENTRENADOR NACIONAL FEB',
        iniciales: 'JG',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 11,
        seccion: 'MARTES Y JUEVES',
        dias: ['Martes', 'Jueves'],
        disciplina: 'BRAZILIAN JIU-JITSU',
        modalidad: 'No-Gi · Avanzado',
        horaInicio: '15:00',
        horaFin: '16:15',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'TATAMI CENTRAL',
        instructor: 'Prof. Mateo Silva',
        cargo: 'FAIXA PRETA 2º DAN IBJJF',
        iniciales: 'MS',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 12,
        seccion: 'MARTES Y JUEVES',
        dias: ['Martes', 'Jueves'],
        disciplina: 'MMA',
        modalidad: 'Grappling & Jaula',
        horaInicio: '16:15',
        horaFin: '17:30',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'OCTÓGONO OFICIAL',
        instructor: 'Marcos Valenzuela',
        cargo: 'LUCHADOR PRO MMA / HEAD COACH',
        iniciales: 'MV',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 13,
        seccion: 'MARTES Y JUEVES',
        dias: ['Martes', 'Jueves'],
        disciplina: 'MUAY THAI',
        modalidad: 'Clínico / Paos',
        horaInicio: '17:30',
        horaFin: '18:45',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'TATAMI 2',
        instructor: 'Carlos "El Toro" Vega',
        cargo: 'KRU CERTIFICADO WBC',
        iniciales: 'CT',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 14,
        seccion: 'MARTES Y JUEVES',
        dias: ['Martes', 'Jueves'],
        disciplina: 'BOXEO',
        modalidad: 'Táctico & Sparring Ligero',
        horaInicio: '18:45',
        horaFin: '20:00',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'RING CENTRAL',
        instructor: 'Javier "Zurdo" Gómez',
        cargo: 'ENTRENADOR NACIONAL FEB',
        iniciales: 'JG',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 15,
        seccion: 'SÁBADOS · MASTERCLASSES & SPARRING',
        dias: ['Sábado'],
        disciplina: 'ACONDICIONAMIENTO',
        modalidad: 'Acondicionamiento Físico',
        horaInicio: '07:00',
        horaFin: '08:00',
        turnoFiltro: 'MAÑANA',
        lugar: 'ZONA DE FUERZA',
        instructor: 'Sergio Ramos B.',
        cargo: 'PREPARADOR FÍSICO CSCS',
        iniciales: 'SR',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 16,
        seccion: 'SÁBADOS · MASTERCLASSES & SPARRING',
        dias: ['Sábado'],
        disciplina: 'MUAY THAI',
        modalidad: 'Masterclass',
        horaInicio: '08:00',
        horaFin: '09:00',
        turnoFiltro: 'MAÑANA',
        lugar: 'TATAMI 1',
        instructor: 'Carlos "El Toro" Vega',
        cargo: 'KRU CERTIFICADO WBC',
        iniciales: 'CT',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 17,
        seccion: 'SÁBADOS · MASTERCLASSES & SPARRING',
        dias: ['Sábado'],
        disciplina: 'BOXEO',
        modalidad: 'Masterclass',
        horaInicio: '09:00',
        horaFin: '10:00',
        turnoFiltro: 'MAÑANA',
        lugar: 'RING CENTRAL',
        instructor: 'Javier "Zurdo" Gómez',
        cargo: 'ENTRENADOR NACIONAL FEB',
        iniciales: 'JG',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 18,
        seccion: 'SÁBADOS · MASTERCLASSES & SPARRING',
        dias: ['Sábado'],
        disciplina: 'MMA',
        modalidad: 'Sparring Supervisado',
        horaInicio: '10:00',
        horaFin: '11:30',
        turnoFiltro: 'MAÑANA',
        lugar: 'JAULA OFICIAL',
        instructor: 'Marcos Valenzuela',
        cargo: 'LUCHADOR PRO MMA / HEAD COACH',
        iniciales: 'MV',
        accionText: 'RESERVAR PLAZA',
        requiereReserva: true,
    },
    {
        id: 19,
        seccion: 'SÁBADOS · MASTERCLASSES & SPARRING',
        dias: ['Sábado'],
        disciplina: 'BRAZILIAN JIU-JITSU',
        modalidad: 'Open Mat · Socios Bushido',
        horaInicio: '15:00',
        horaFin: '16:30',
        turnoFiltro: 'TARDE / NOCHE',
        lugar: 'TATAMI LIBRE',
        instructor: 'Prof. Mateo Silva',
        cargo: 'TATAMI LIBRE & DRILL',
        iniciales: 'MS',
        accionText: 'ENTRADA LIBRE (SOCIOS)',
        requiereReserva: false,
    },
];
